# SPDX-License-Identifier: GPL-2.0
# Compiler flags, which are necessary to build userspace applications with the
# in-kernel libc "nolibc".

ifeq ($(and $(CONFIG_ARCH_HAS_NOLIBC),$(CONFIG_HEADERS_INSTALL)),y)

NOLIBC_USERCFLAGS := -nostdlib -nostdinc -static -ffreestanding \
		     -fno-asynchronous-unwind-tables -fno-stack-protector \
		     -isystem $(objtree)/usr/include -isystem $(srctree)/tools/include/nolibc/

NOLIBC_USERLDFLAGS := -nostdlib -nostdinc -static

ifdef CONFIG_ARM
NOLIBC_USERCFLAGS += -march=armv8-a
endif
ifeq ($(CONFIG_MIPS)$(CONFIG_CPU_LITTLE_ENDIAN),yy)
NOLIBC_USERCFLAGS += -EL
NOLIBC_USERLDFLAGS += -EL
endif
ifdef CONFIG_PPC32
NOLIBC_USERCFLAGS += -mno-vsx -mcpu=power3
endif

endif # CONFIG_ARCH_HAS_NOLIBC && CONFIG_HEADERS_INSTALL
